name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.7, 3.8]
        chrome-version: ['83.0.4103.39']
        os: [ubuntu-latest, ubuntu-16.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Chrome driver ${{ matrix.chrome-version }}
      uses: nanasess/setup-chromedriver@master
      with:
        chromedriver-version: ${{ matrix.chrome-version }}
    - name: Set up Chrome driver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Install dependencies (for mac)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
        brew install Caskroom/cask/wkhtmltopdf
        brew upgrade gcc
    - name: Install dependencies (for linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update –fix-missing
        sudo apt-get install xvfb libfontconfig wkhtmltopdf
        sudo apt-get install -y cmake gcc g++
    - name: Set up Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      continue-on-error: true
      timeout-minutes: 30
      run: |
        pip install pytest-github-actions-annotate-failures
        pytest tests --doctest-modules --doctest-modules --junitxml=junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.chrome-version }}.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v1
      with:
        name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.chrome-version }}
        path: junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.chrome-version }}.xml
      if: ${{ always() }}